# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E7DDE2
background         #211A22
cursor             #8B748F

active_tab_foreground     #211A22
active_tab_background     #E7DDE2
inactive_tab_foreground   #E7DDE2
inactive_tab_background   #211A22

active_border_color   #E7DDE2
inactive_border_color #211A22
bell_border_color     #23082E

color0      #48404A
color1		#23082E
color2		#23082E
color3		#310E43
color4		#5E3765
color5		#5E3765
color6		#8C7680
color7		#D5C6CD
color8		#958B8F
color9		#2F0A3D
color10		#2F0A3D
color11		#41125A
color12		#7D4987
color13		#7D4987
color14		#BB9EAB
color15		#D5C6CD
