# --- AUTOSTART ---

# Temas y Colores
#exec-once = wallust -s run ~/wallpapers/default.jpg
source = ~/.config/hypr/wallust/wallust-hyprland.conf

# Interfaz
exec-once = qs
# exec-once = linux-wallpaperengine --fps 24 --no-audio-processing --disable-particles --disable-mouse --silent --screen-root DP-1 --bg /home/mia/wallpapers/2503301542 --screen-root DP-2 --bg /home/mia/wallpapers/2587542891
exec-once = awww-daemon
exec-once = sleep 1 && awww img /home/mia/wallpapers/snapshots/DP-1_4k.png -o DP-1
exec-once = sleep 1 && awww img /home/mia/wallpapers/snapshots/DP-2_4k.png -o DP-2
# exec-once = hyprpaper


# Applets y Servicios
exec-once = hyprshade off # Asegura pantalla limpia al inicio
exec-once = nm-applet --indicator
exec-once = blueman-applet #BT
exec-once = nwg-look -a # Aplica el tema GTK, iconos y cursores
exec-once = swaync #Notification
exec-once = fcitx5 -d # keyboard layouts
exec-once = hypridle # Cerebro de bloqueo e inactividad
# widget de escritorio (Desactivado - Migrado a Quickshell)
# exec-once = eww daemon
# exec-once = eww open-many desktop-1 desktop-0

#clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store