# Pre-carga de imágenes
preload = /home/mia/wallpapers/2503301542/preview.jpg
preload = /home/mia/wallpapers/2587542891/preview.jpg

# Asignación a monitores
# Monitor principal (DP-1)
wallpaper = DP-1, /home/mia/wallpapers/2503301542/preview.jpg
# Monitor secundario (DP-2)
wallpaper = DP-2, /home/mia/wallpapers/2587542891/preview.jpg

# Desactivar splash (el texto de abajo)
splash = false
