# #######################################################################################
# CONFIGURACIÓN MODULAR DE HYPRLAND
# #######################################################################################

# 1. Monitores y Workspaces (Gestionado por nwg-displays)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf

# 2. Variables de Entorno (Cargar antes que nada)
source = ~/.config/hypr/envs.conf

# 3. Autostart y Apps al inicio
source = ~/.config/hypr/autostart.conf

# 4. Estética y Configuración General
source = ~/.config/hypr/settings.conf

# 5. Animaciones
source = ~/.config/hypr/animations.conf

# 6. Atajos de Teclado
source = ~/.config/hypr/keybindings.conf

# 7. Reglas de Ventanas (Próximamente)
# source = ~/.config/hypr/windowrules.conf
